spring.config.import=optional:application-secret.properties

spring.application.name=soso
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.qdrant.autoconfigure.QdrantVectorStoreAutoConfiguration

server.port=8080
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.expiration=86400000

# MyBatis Config
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.soso.domain.member.dto
mybatis.configuration.map-underscore-to-camel-case=true

#gcs
spring.cloud.gcp.storage.credentials.location=classpath:secure/gcs_key.json
spring.cloud.gcp.credentials.location=classpath:secure/gcs_key.json
spring.cloud.gcp.bucket=study_jcr

api.public-data.service-key=${ownerCheck.key}


spring.profiles.include=secret
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# 포트원 상점 ID
portone.store-id=store-d07c8343-3eda-4b37-b1b1-d59c24f3d02d

# 포트원 채널 키
portone.channel-key=channel-key-3ac881ab-bc4c-4016-b0d0-3c6eb420b83c

# 포트원 API Secret
# 이 값은 절대 프론트에 넣으면 안 됨
portone.api-secret=yQIWAB34sri25n0aZY7PcFcaSQ4zRqUPHSQhymdih9SC1ff2XUPX5tXZaOVqddOYywm4xTkx1EagMKFD